version: "3.8"
services:
  backend:
    build: ./backend
    ports: 
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
     build: ./frontend
     ports:
      - '3000:3000'
     depends_on:
      - backend
     volumes:
      - ./frontend/src:/app/src
     stdin_open: true
     tty: true
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/data/db
    # container_name: exampe
    env_file:
      - ./env/mongo.env
volumes:
  data:
  logs:
    

